name: Custom Action Demo
on:
  push:
    branches:
      - main

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: calling custom action yml
        id: greet
        uses: ./
        with:
          username: Kulbhushan
      - name: Use Action output
        run: echo "Action says: ${{ steps.greet.outputs.message }}"
